import { useEffect, useRef, useState, type FormEvent } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Clock3, Loader2, Search, Sparkles, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { ProductImage } from "@/components/product-image";
import { useFormatPrice } from "@/lib/currency-context";

type Suggestion = { id:string; name:string; price:number; old_price:number|null; images:string[]; badge:string|null };
const RECENT_KEY="shehara_recent_searches_v1";

function recent():string[]{ try { const v=JSON.parse(localStorage.getItem(RECENT_KEY)||"[]"); return Array.isArray(v)?v.filter((x):x is string=>typeof x==="string").slice(0,5):[]; } catch { return []; } }
function remember(q:string){ try { localStorage.setItem(RECENT_KEY,JSON.stringify([q,...recent().filter(x=>x!==q)].slice(0,5))); } catch {} }

export function ProductSearch({open,onClose}:{open:boolean;onClose:()=>void}){
 const navigate=useNavigate(); const formatPrice=useFormatPrice(); const inputRef=useRef<HTMLInputElement>(null);
 const [q,setQ]=useState(""); const [rows,setRows]=useState<Suggestion[]>([]); const [recentRows,setRecentRows]=useState<string[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(false);
 useEffect(()=>{if(!open)return;setRecentRows(recent());const t=setTimeout(()=>inputRef.current?.focus(),80);return()=>clearTimeout(t)},[open]);
 useEffect(()=>{if(!open)return;const term=q.trim();if(!term){setRows([]);setLoading(false);return}let cancelled=false;setLoading(true);setError(false);const t=setTimeout(()=>{void supabase.from("products").select("id,name,price,old_price,images,badge").eq("is_active",true).ilike("name",`%${term}%`).order("sales_count",{ascending:false}).limit(7).then(({data,error})=>{if(cancelled)return;if(error)throw error;setRows((data||[]).map((p:any)=>({id:String(p.id),name:String(p.name||""),price:Number(p.price)||0,old_price:p.old_price==null?null:Number(p.old_price)||0,images:Array.isArray(p.images)?p.images:[],badge:p.badge?String(p.badge):null})))}).catch(()=>{if(!cancelled){setRows([]);setError(true)}}).finally(()=>{if(!cancelled)setLoading(false)})},180);return()=>{cancelled=true;clearTimeout(t)}},[q,open]);
 useEffect(()=>{if(!open)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";const esc=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose()};window.addEventListener("keydown",esc);return()=>{document.body.style.overflow=old;window.removeEventListener("keydown",esc)}},[open,onClose]);
 if(!open)return null;
 const submit=(e?:FormEvent)=>{e?.preventDefault();const term=q.trim();if(!term)return;remember(term);setRecentRows(recent());onClose();void navigate({to:"/products",search:{q:term}})};
 return <div dir="rtl" className="fixed inset-0 z-[15000] flex items-start justify-center bg-[#06151D]/60 pt-[env(safe-area-inset-top)] backdrop-blur-md sm:p-4 sm:pt-[calc(env(safe-area-inset-top)+1rem)]" role="dialog" aria-modal="true" aria-label="البحث عن المنتجات" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}>
  <div className="flex h-[100dvh] w-full flex-col overflow-hidden bg-background shadow-2xl sm:h-auto sm:max-h-[760px] sm:max-w-2xl sm:rounded-[28px] sm:border sm:border-border/70">
   <div className="border-b border-border/70 px-4 pb-4 pt-4 sm:px-5"><div className="mb-3 flex items-center justify-between"><div><p className="text-[9px] font-black tracking-[.16em] text-[#D65A31]">SHEHARA SEARCH</p><h2 className="mt-1 text-lg font-black text-[#0E4D64] dark:text-white">ابحث عن منتجاتك</h2></div><button onClick={onClose} aria-label="إغلاق البحث" className="grid h-10 w-10 place-items-center rounded-2xl bg-muted text-muted-foreground active:scale-90"><X className="h-5 w-5"/></button></div>
    <form onSubmit={submit}><div className="flex h-14 items-center gap-2 rounded-[20px] border border-[#0E4D64]/10 bg-[#F5F8F9] px-3 focus-within:ring-4 focus-within:ring-[#0E4D64]/[.06] dark:bg-white/[.045]"><Search className="h-5 w-5 text-[#0E4D64]"/><input ref={inputRef} value={q} onChange={e=>setQ(e.target.value)} type="search" autoComplete="off" enterKeyHint="search" placeholder="ابحث عن منتج..." className="min-w-0 flex-1 bg-transparent text-sm font-bold outline-none"/>{loading?<Loader2 className="h-5 w-5 animate-spin text-[#D65A31]"/>:q?<button type="button" onClick={()=>{setQ("");inputRef.current?.focus()}} className="grid h-9 w-9 place-items-center rounded-xl"><X className="h-4 w-4"/></button>:null}</div></form>
   </div>
   <div className="min-h-0 flex-1 overflow-y-auto p-3 sm:p-4">
    {!q.trim()?<div className="p-2"><div className="mb-3 flex items-center gap-2"><Clock3 className="h-4 w-4 text-[#D65A31]"/><span className="text-xs font-black">عمليات البحث الأخيرة</span></div>{recentRows.length?<div className="flex flex-wrap gap-2">{recentRows.map(x=><button key={x} onClick={()=>{setQ(x);inputRef.current?.focus()}} className="rounded-full border border-border px-3 py-2 text-[11px] font-bold active:scale-95">{x}</button>)}</div>:<div className="rounded-2xl border border-dashed border-border p-8 text-center"><Sparkles className="mx-auto h-5 w-5 text-[#D65A31]"/><p className="mt-2 text-xs text-muted-foreground">اكتب اسم المنتج لتظهر الاقتراحات مباشرة.</p></div>}</div>:error?<div className="p-8 text-center text-xs text-muted-foreground">تعذر تحميل اقتراحات المنتجات حاليًا.</div>:rows.length?<div><p className="px-2 pb-2 text-[10px] font-black text-muted-foreground">اقتراحات المنتجات</p>{rows.map(p=><Link key={p.id} to="/product/$id" params={{id:p.id}} onClick={onClose} className="group flex items-center gap-3 rounded-2xl p-2.5 hover:bg-[#0E4D64]/[.045]"><ProductImage src={p.images[0]} alt={p.name} className="h-14 w-14 shrink-0 rounded-xl"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-black">{p.name}</p><div className="mt-1 flex items-center gap-2"><b className="text-xs text-[#0E4D64] dark:text-white">{formatPrice(p.price)}</b>{p.old_price&&p.old_price>p.price?<span className="text-[9px] line-through text-muted-foreground">{formatPrice(p.old_price)}</span>:null}</div></div><ArrowLeft className="h-4 w-4 text-muted-foreground group-hover:text-[#D65A31]"/></Link>)}<button onClick={()=>submit()} className="mt-2 flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[#0E4D64] text-xs font-black text-white active:scale-[.99]">عرض كل النتائج عن «{q.trim()}»<ArrowLeft className="h-4 w-4"/></button></div>:loading?<div className="space-y-2">{Array.from({length:5}).map((_,i)=><div key={i} className="flex gap-3 p-2"><div className="h-14 w-14 animate-pulse rounded-xl bg-muted"/><div className="flex-1 space-y-2 pt-2"><div className="h-3 w-3/4 animate-pulse rounded bg-muted"/><div className="h-3 w-1/3 animate-pulse rounded bg-muted"/></div></div>)}</div>:<div className="rounded-2xl border border-dashed border-border p-10 text-center"><Search className="mx-auto h-7 w-7 text-muted-foreground/50"/><p className="mt-3 text-sm font-black">لا توجد منتجات مطابقة</p><p className="mt-1 text-[11px] text-muted-foreground">جرّب كلمة أخرى.</p><button onClick={()=>submit()} className="mt-4 rounded-xl bg-[#D65A31] px-4 py-2.5 text-[11px] font-black text-white">البحث عن «{q.trim()}»</button></div>}
   </div>
  </div>
 </div>
}
export default ProductSearch;
