import { Link, useLocation } from "@tanstack/react-router";
import { Moon, Search, Sun } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { SideMenu } from "@/components/side-menu";
import { NotificationBell } from "@/components/notification-bell";
import { BrandLogo } from "@/components/brand-logo";
import { ProductSearch } from "@/components/product-search";

const THEME_STORAGE_KEY="shehara-theme";
export function SiteHeader(){
 const location=useLocation(); const [darkMode,setDarkMode]=useState(false); const [searchOpen,setSearchOpen]=useState(false); const searchRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{try{const saved=localStorage.getItem(THEME_STORAGE_KEY);if(saved==="dark"||saved==="light"){document.documentElement.classList.toggle("dark",saved==="dark");document.documentElement.style.colorScheme=saved;document.documentElement.dataset.theme=saved;setDarkMode(saved==="dark");return}}catch{}setDarkMode(document.documentElement.classList.contains("dark"))},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setSearchOpen(true)}if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"&&document.activeElement?.tagName!=="TEXTAREA"){e.preventDefault();setSearchOpen(true)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
 const toggle=()=>{const next=!darkMode;document.documentElement.classList.toggle("dark",next);document.documentElement.style.colorScheme=next?"dark":"light";document.documentElement.dataset.theme=next?"dark":"light";setDarkMode(next);try{localStorage.setItem(THEME_STORAGE_KEY,next?"dark":"light")}catch{}};
 return <><header className="fixed inset-x-0 top-0 z-[100] w-full border-b border-[color:var(--border)]/70 bg-[color:var(--background)]/94 shadow-[0_10px_30px_-26px_rgba(14,77,100,.8)] backdrop-blur-2xl supports-[backdrop-filter]:bg-[color:var(--background)]/82"><div className="pt-[env(safe-area-inset-top)]"><div className="relative mx-auto flex h-[62px] w-full max-w-7xl items-center justify-between px-3 sm:h-[66px] sm:px-5 lg:px-8"><div className="flex items-center gap-1"><SideMenu/><button type="button" onClick={toggle} aria-label={darkMode?"تفعيل الوضع الفاتح":"تفعيل الوضع الداكن"} className="grid h-10 w-10 place-items-center rounded-2xl text-[#0E4D64] hover:bg-[#0E4D64]/[.07] hover:text-[#D65A31] active:scale-90 dark:text-[#DDECF0]">{darkMode?<Sun className="h-5 w-5"/>:<Moon className="h-5 w-5"/>}</button></div><Link to="/" aria-label="شهارة - تسوق بلا حدود" className="absolute start-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-2xl p-1.5 transition-transform hover:scale-[1.03] active:scale-95"><span className="flex h-12 w-12 items-center justify-center rounded-2xl border border-[#0E4D64]/[.06] bg-white shadow-[0_10px_28px_-22px_rgba(14,77,100,.8)] dark:border-white/[.07] dark:bg-white/[.04]"><BrandLogo size={46} className="h-10 w-10 sm:h-11 sm:w-11" priority/></span></Link><div className="ms-auto flex items-center gap-1"><NotificationBell/><button ref={searchRef} type="button" onClick={()=>setSearchOpen(true)} aria-label="البحث عن المنتجات" aria-haspopup="dialog" aria-expanded={searchOpen} className="grid h-10 w-10 place-items-center rounded-2xl text-[#0E4D64] hover:bg-[#0E4D64]/[.07] hover:text-[#D65A31] active:scale-90 dark:text-[#DDECF0]"><Search className="h-5 w-5" strokeWidth={2.15}/></button></div></div></div></header><div aria-hidden="true" className="h-[calc(66px+env(safe-area-inset-top))]"/><ProductSearch open={searchOpen} onClose={()=>{setSearchOpen(false);searchRef.current?.focus()}}/><span className="sr-only">{location.pathname}</span></>;
}
export default SiteHeader;
