// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role / secret key.
// Use this for trusted server-side operations only.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(
  value: string,
): boolean {
  return (
    value.startsWith("sb_publishable_") ||
    value.startsWith("sb_secret_")
  );
}

/**
 * Supabase secret keys may be exposed by
 * Lovable/Supabase using different environment
 * variable names depending on the project/runtime.
 *
 * Priority:
 * 1. SUPABASE_SECRET_KEYS
 * 2. SUPABASE_SECRET_KEY
 * 3. SUPABASE_SERVICE_ROLE_KEY
 */
function getSupabaseSecretKey():
  | string
  | undefined {
  const secretKeys =
    process.env[
      "SUPABASE_SECRET_KEYS"
    ];

  if (
    secretKeys &&
    secretKeys.trim()
  ) {
    try {
      const parsed =
        JSON.parse(secretKeys);

      if (
        parsed &&
        typeof parsed === "object"
      ) {
        const defaultKey =
          parsed.default;

        if (
          typeof defaultKey ===
            "string" &&
          defaultKey.trim()
        ) {
          return defaultKey.trim();
        }

        const firstKey =
          Object.values(
            parsed,
          ).find(
            (value) =>
              typeof value ===
                "string" &&
              value.trim(),
          );

        if (
          typeof firstKey ===
          "string"
        ) {
          return firstKey.trim();
        }
      }
    } catch {
      /*
       * بعض البيئات قد توفر المفتاح
       * كنص مباشر بدلاً من JSON.
       */
      const direct =
        secretKeys.trim();

      if (direct) {
        return direct;
      }
    }
  }

  const singular =
    process.env[
      "SUPABASE_SECRET_KEY"
    ];

  if (
    singular &&
    singular.trim()
  ) {
    return singular.trim();
  }

  const legacy =
    process.env[
      "SUPABASE_SERVICE_ROLE_KEY"
    ];

  if (
    legacy &&
    legacy.trim()
  ) {
    return legacy.trim();
  }

  return undefined;
}

function createSupabaseFetch(
  supabaseKey: string,
): typeof fetch {
  return (
    input,
    init,
  ) => {
    const headers =
      new Headers(
        typeof Request !==
          "undefined" &&
        input instanceof Request
          ? input.headers
          : undefined,
      );

    if (init?.headers) {
      new Headers(
        init.headers,
      ).forEach(
        (
          value,
          key,
        ) =>
          headers.set(
            key,
            value,
          ),
      );
    }

    /*
     * New Supabase API keys are opaque
     * strings and should be sent through
     * the apikey header.
     */
    if (
      isNewSupabaseApiKey(
        supabaseKey,
      ) &&
      headers.get(
        "Authorization",
      ) ===
        `Bearer ${supabaseKey}`
    ) {
      headers.delete(
        "Authorization",
      );
    }

    headers.set(
      "apikey",
      supabaseKey,
    );

    return fetch(
      input,
      {
        ...init,
        headers,
      },
    );
  };
}

function createSupabaseAdminClient() {
  const supabaseUrl =
    process.env[
      "SUPABASE_URL"
    ];

  const supabaseSecretKey =
    getSupabaseSecretKey();

  if (
    !supabaseUrl ||
    !supabaseSecretKey
  ) {
    const missing: string[] =
      [];

    if (!supabaseUrl) {
      missing.push(
        "SUPABASE_URL",
      );
    }

    if (!supabaseSecretKey) {
      missing.push(
        "SUPABASE_SECRET_KEY / SUPABASE_SERVICE_ROLE_KEY",
      );
    }

    const message =
      `Missing Supabase environment variable(s): ${missing.join(
        ", ",
      )}. Connect Supabase in Lovable Cloud.`;

    console.error(
      `[Supabase] ${message}`,
    );

    throw new Error(
      message,
    );
  }

  return createClient<Database>(
    supabaseUrl,
    supabaseSecretKey,
    {
      global: {
        fetch:
          createSupabaseFetch(
            supabaseSecretKey,
          ),
      },

      auth: {
        storage:
          undefined,
        persistSession:
          false,
        autoRefreshToken:
          false,
      },
    },
  );
}

let supabaseAdminInstance:
  | ReturnType<
      typeof createSupabaseAdminClient
    >
  | undefined;

/**
 * Server-side Supabase client.
 *
 * IMPORTANT:
 * This proxy initializes the client lazily,
 * so merely importing this module does not
 * require the secret key.
 */
export const supabaseAdmin =
  new Proxy(
    {} as ReturnType<
      typeof createSupabaseAdminClient
    >,
    {
      get(
        _target,
        property,
        receiver,
      ) {
        if (
          !supabaseAdminInstance
        ) {
          supabaseAdminInstance =
            createSupabaseAdminClient();
        }

        return Reflect.get(
          supabaseAdminInstance,
          property,
          receiver,
        );
      },
    },
  );
